import {z} from 'zod';
export const movementSchema=z.object({lotId:z.string().min(1),movementType:z.enum(['RECEIVE','MOVE','ISSUE','RETURN','ADJUST','PICK','DISPATCH']),qtyKg:z.coerce.number().nonnegative(),fromBinCode:z.string().optional(),toBinCode:z.string().optional(),refType:z.string().optional(),refId:z.string().optional()}).superRefine((d,ctx)=>{
  if(d.movementType!=='ADJUST'&&d.qtyKg<=0)ctx.addIssue({code:'custom',path:['qtyKg'],message:'الكمية يجب أن تكون أكبر من صفر'});
  if(d.movementType==='MOVE'){
    if(!d.fromBinCode)ctx.addIssue({code:'custom',path:['fromBinCode'],message:'موقع التخزين المصدر مطلوب للنقل'});
    if(!d.toBinCode)ctx.addIssue({code:'custom',path:['toBinCode'],message:'موقع التخزين الوجهة مطلوب للنقل'});
    if(d.fromBinCode&&d.toBinCode&&d.fromBinCode===d.toBinCode)ctx.addIssue({code:'custom',path:['toBinCode'],message:'يجب أن يختلف موقع الوجهة عن المصدر'});
  }
});
export const productionOrderSchema=z.object({productId:z.string().min(1),machineId:z.string().min(1),plannedQtyKg:z.coerce.number().positive(),plannedStart:z.coerce.date(),plannedEnd:z.coerce.date().optional(),priority:z.enum(['LOW','NORMAL','HIGH','URGENT']).default('NORMAL')});
export const startRunSchema=z.object({productionOrderId:z.string().min(1),shiftId:z.string().min(1),poyLotId:z.string().min(1),poyIssueKg:z.coerce.number().positive()});
export const completeRunSchema=z.object({gradeAKg:z.coerce.number().nonnegative(),gradeBKg:z.coerce.number().nonnegative(),wasteKg:z.coerce.number().nonnegative(),electricityKwh:z.coerce.number().nonnegative(),downtimeMin:z.coerce.number().int().nonnegative().default(0)});
export const qualityHoldSchema=z.object({refType:z.enum(['INVENTORY_LOT','FINISHED_LOT']),refId:z.string().min(1),reason:z.string().min(3)});
export const prCreateSchema=z.object({requiredDate:z.coerce.date().optional(),notes:z.string().optional(),lines:z.array(z.object({materialId:z.string().min(1),qtyKg:z.coerce.number().positive(),suggestedSupplierId:z.string().optional(),source:z.string().optional()})).min(1)});
export const poCreateSchema=z.object({supplierId:z.string().min(1),currency:z.string().default('USD'),exchangeRate:z.coerce.number().positive(),paymentTermsDays:z.coerce.number().int().nonnegative().default(0),lines:z.array(z.object({materialId:z.string().min(1),qtyKg:z.coerce.number().positive(),unitPrice:z.coerce.number().positive(),sourcePrLineId:z.string().optional()})).min(1)});
export const receiptSchema=z.object({poId:z.string().min(1),containerNo:z.string().optional(),blNo:z.string().optional(),freightEgp:z.coerce.number().nonnegative().default(0),insuranceEgp:z.coerce.number().nonnegative().default(0),bankChargesEgp:z.coerce.number().nonnegative().default(0),customsCostEgp:z.coerce.number().nonnegative().default(0),inlandCostEgp:z.coerce.number().nonnegative().default(0),lines:z.array(z.object({poLineId:z.string().min(1),lotNo:z.string().min(3),qtyKg:z.coerce.number().positive()})).min(1)});
export const salesOrderCreateSchema=z.object({customerId:z.string().min(1),currency:z.string().default('EGP'),paymentTermsDays:z.coerce.number().int().nonnegative().optional(),lines:z.array(z.object({productId:z.string().min(1),qtyKg:z.coerce.number().positive(),unitPrice:z.coerce.number().positive(),requiredDate:z.coerce.date()})).min(1)});
export const collectionSchema=z.object({invoiceId:z.string().min(1),amount:z.coerce.number().positive(),method:z.string().min(2),reference:z.string().optional()});
export const downtimeEventSchema=z.object({productionRunId:z.string().min(1),codeId:z.string().min(1),durationMin:z.coerce.number().int().positive(),notes:z.string().optional()});
export const maintenanceOrderSchema=z.object({machineId:z.string().min(1),type:z.string().min(2),priority:z.enum(['LOW','NORMAL','HIGH','URGENT']).default('NORMAL'),notes:z.string().optional()});
export const maintenanceCompleteSchema=z.object({rootCause:z.string().min(2),laborHours:z.coerce.number().nonnegative().default(0),externalCost:z.coerce.number().nonnegative().default(0),spares:z.array(z.object({sparePartId:z.string().min(1),qty:z.coerce.number().positive()})).default([])});
export const calculateCostSchema=z.object({productionRunId:z.string().min(1)});

export const customerAdjustmentSchema=z.object({customerId:z.string().min(1),salesOrderId:z.string().optional(),type:z.enum(['FREIGHT','CLAIM','DISCOUNT','RETURN','OTHER']),amountEgp:z.coerce.number().positive(),occurredAt:z.coerce.date().optional(),notes:z.string().optional()});
export const supplierInvoiceSchema=z.object({supplierId:z.string().min(1),purchaseOrderId:z.string().optional(),invoiceNo:z.string().min(2),invoiceDate:z.coerce.date().optional(),dueDate:z.coerce.date(),totalAmount:z.coerce.number().positive(),currency:z.string().default('USD'),exchangeRate:z.coerce.number().positive().default(1),notes:z.string().optional()});
export const supplierPaymentSchema=z.object({supplierInvoiceId:z.string().min(1),amount:z.coerce.number().positive(),method:z.string().min(2),reference:z.string().optional()});
export const stockCountCreateSchema=z.object({warehouseId:z.string().min(1),notes:z.string().optional()});
export const stockCountSubmitSchema=z.object({lines:z.array(z.object({lineId:z.string().min(1),countedQtyKg:z.coerce.number().nonnegative(),note:z.string().optional()})).min(1)});
export const materialUpsertSchema=z.object({id:z.string().optional(),code:z.string().min(3),nameAr:z.string().min(2),type:z.enum(['POY','PACKAGING','SPARE','OTHER']),denier:z.coerce.number().positive().optional(),filaments:z.coerce.number().int().positive().optional(),lustre:z.enum(['SD','BRIGHT','FULL_DULL','TRILOBAL','OTHER']).optional(),uom:z.string().default('kg'),safetyStockKg:z.coerce.number().nonnegative().default(0),active:z.boolean().default(true)});
export const productUpsertSchema=z.object({id:z.string().optional(),code:z.string().min(3),nameAr:z.string().min(2),denier:z.coerce.number().positive(),filaments:z.coerce.number().int().positive(),intermingle:z.enum(['NIM','SIM','HIM','NONE']),lustre:z.enum(['SD','BRIGHT','FULL_DULL','TRILOBAL','OTHER']),standardYield:z.coerce.number().min(.8).max(1),standardPackKg:z.coerce.number().positive().optional(),rawMaterialId:z.string().optional(),active:z.boolean().default(true)});
export const supplierUpsertSchema=z.object({id:z.string().optional(),code:z.string().min(2),nameAr:z.string().min(2),country:z.string().optional(),currencyDefault:z.string().default('USD'),paymentTermsDays:z.coerce.number().int().nonnegative().default(0),qualityStatus:z.string().default('APPROVED')});
export const customerUpsertSchema=z.object({id:z.string().optional(),code:z.string().min(2),nameAr:z.string().min(2),city:z.string().optional(),customerType:z.string().optional(),creditLimit:z.coerce.number().nonnegative(),paymentTermsDays:z.coerce.number().int().nonnegative().default(0),blocked:z.boolean().default(false)});
export const systemSettingSchema=z.object({key:z.string().min(2),value:z.any(),plantId:z.string().optional()});
export const adminUserSchema=z.object({id:z.string().optional(),username:z.string().min(3),fullNameAr:z.string().min(2),mobile:z.string().optional(),password:z.string().min(8).optional(),active:z.boolean().default(true),roleCodes:z.array(z.string().min(2)).min(1),plantId:z.string().optional()});
export const qualityTestBatchSchema=z.object({finishedLotId:z.string().min(1),sampleNo:z.string().min(3),tests:z.array(z.object({specId:z.string().min(1),resultValue:z.coerce.number()})).min(1)});
export const productionPlanSchema=z.object({startDate:z.coerce.date(),endDate:z.coerce.date(),notes:z.string().optional(),lines:z.array(z.object({productId:z.string().min(1),machineId:z.string().min(1),plannedQtyKg:z.coerce.number().positive(),plannedStart:z.coerce.date(),plannedEnd:z.coerce.date().optional(),priority:z.enum(['LOW','NORMAL','HIGH','URGENT']).default('NORMAL')})).min(1)});
export const rfqSchema=z.object({dueDate:z.coerce.date(),notes:z.string().optional(),lines:z.array(z.object({materialId:z.string().min(1),qtyKg:z.coerce.number().positive(),requiredDate:z.coerce.date().optional()})).min(1)});
export const supplierQuoteSchema=z.object({rfqId:z.string().min(1),supplierId:z.string().min(1),currency:z.string().default('USD'),exchangeRate:z.coerce.number().positive().default(1),validUntil:z.coerce.date().optional(),paymentTermsDays:z.coerce.number().int().nonnegative().default(0),lines:z.array(z.object({rfqLineId:z.string().min(1),unitPrice:z.coerce.number().positive(),freightEgpKg:z.coerce.number().nonnegative().default(0),leadTimeDays:z.coerce.number().int().nonnegative().default(0)})).min(1)});
export const salesQuotationSchema=z.object({customerId:z.string().min(1),currency:z.string().default('EGP'),validUntil:z.coerce.date(),paymentTermsDays:z.coerce.number().int().nonnegative().default(0),lines:z.array(z.object({productId:z.string().min(1),qtyKg:z.coerce.number().positive(),unitPrice:z.coerce.number().positive(),requiredDate:z.coerce.date()})).min(1)});
export const machineUpsertSchema=z.object({id:z.string().optional(),code:z.string().min(2),nameAr:z.string().min(2),origin:z.string().min(2),year:z.coerce.number().int().min(1980).max(2100),spindles:z.coerce.number().int().positive(),status:z.enum(['RUN','STOP','MAINT','TRIAL']).default('RUN')});
export const shiftUpsertSchema=z.object({id:z.string().optional(),code:z.string().min(1),nameAr:z.string().min(2),startTime:z.string().min(4),endTime:z.string().min(4)});
export const warehouseUpsertSchema=z.object({id:z.string().optional(),code:z.string().min(2),nameAr:z.string().min(2),type:z.string().min(2)});
