import {prisma} from '@/lib/prisma';import {requirePermission,apiError} from '@/lib/rbac';import {downtimeEventSchema} from '@/lib/validators';import {audit} from '@/lib/audit';import {enqueueIntegrationEvent} from '@/lib/integrations';
export async function GET(){try{const s=await requirePermission('production.read');const codes=await prisma.downtimeCode.findMany({orderBy:{category:'asc'}});const openRuns=await prisma.productionRun.findMany({where:{status:'OPEN',productionOrder:{machine:{plantId:s.plantId}}},include:{productionOrder:{include:{machine:true,product:true}},downtimeEvents:{where:{endTime:null},include:{code:true}}}});return Response.json({ok:true,codes,openRuns});}catch(e){return apiError(e)}}
export async function POST(req:Request){try{const s=await requirePermission('production.run');const raw=await req.json();
 if(raw.action==='START'){
  const productionRunId=String(raw.productionRunId||''),codeId=String(raw.codeId||'');if(!productionRunId||!codeId)throw Object.assign(new Error('التشغيل وسبب التوقف مطلوبان'),{status:400});
  const ev=await prisma.$transaction(async tx=>{const run=await tx.productionRun.findUnique({where:{id:productionRunId},include:{productionOrder:{include:{machine:true}}}});if(!run||run.status!=='OPEN'||run.productionOrder.machine.plantId!==s.plantId)throw Object.assign(new Error('التشغيل المفتوح غير موجود'),{status:404});const locked=await tx.productionRun.updateMany({where:{id:productionRunId,status:'OPEN'},data:{status:'OPEN'}});if(locked.count!==1)throw Object.assign(new Error('التشغيل المفتوح غير موجود'),{status:409});const open=await tx.downtimeEvent.findFirst({where:{productionRunId,endTime:null}});if(open)throw Object.assign(new Error('يوجد توقف مفتوح بالفعل على هذه الماكينة'),{status:409});const code=await tx.downtimeCode.findUnique({where:{id:codeId}});if(!code)throw Object.assign(new Error('سبب التوقف غير موجود'),{status:404});const e=await tx.downtimeEvent.create({data:{productionRunId,codeId,startTime:new Date(),notes:raw.notes||null}});await tx.machine.update({where:{id:run.productionOrder.machineId},data:{status:'STOP'}});await audit(tx,{userId:s.userId,entityType:'DowntimeEvent',entityId:e.id,action:'START',after:{code:code.code}});await enqueueIntegrationEvent(tx,{companyId:s.companyId,plantId:s.plantId,eventType:'DOWNTIME_STARTED',payload:{eventId:e.id,machineCode:run.productionOrder.machine.code,runId:run.id,reason:code.nameAr}});return {...e,code}});return Response.json({ok:true,event:ev},{status:201});
 }
 if(raw.action==='STOP'){
  const ev=await prisma.$transaction(async tx=>{const open=raw.eventId?await tx.downtimeEvent.findUnique({where:{id:String(raw.eventId)},include:{code:true,productionRun:{include:{productionOrder:{include:{machine:true}}}}}}):await tx.downtimeEvent.findFirst({where:{productionRunId:String(raw.productionRunId||''),endTime:null},include:{code:true,productionRun:{include:{productionOrder:{include:{machine:true}}}}}});if(!open||open.endTime)throw Object.assign(new Error('لا يوجد توقف مفتوح'),{status:404});if(open.productionRun.productionOrder.machine.plantId!==s.plantId)throw Object.assign(new Error('FORBIDDEN'),{status:403});const end=new Date();const durationMin=Math.max(1,Math.ceil((end.getTime()-new Date(open.startTime).getTime())/60000));const claimed=await tx.downtimeEvent.updateMany({where:{id:open.id,endTime:null},data:{endTime:end,durationMin}});if(claimed.count!==1)throw Object.assign(new Error('تم إغلاق التوقف بالفعل'),{status:409});const e=await tx.downtimeEvent.findUniqueOrThrow({where:{id:open.id}});await tx.productionRun.update({where:{id:open.productionRunId},data:{downtimeMin:{increment:durationMin}}});await tx.machine.update({where:{id:open.productionRun.productionOrder.machineId},data:{status:'RUN'}});await audit(tx,{userId:s.userId,entityType:'DowntimeEvent',entityId:e.id,action:'STOP',after:{durationMin}});const threshold=Number(process.env.DOWNTIME_ALERT_MINUTES||30);if(durationMin>=threshold)await enqueueIntegrationEvent(tx,{companyId:s.companyId,plantId:s.plantId,eventType:'LONG_DOWNTIME',payload:{eventId:e.id,machineCode:open.productionRun.productionOrder.machine.code,durationMin,reason:open.code.nameAr}});return {...e,durationMin}});return Response.json({ok:true,event:ev});
 }
 const d=downtimeEventSchema.parse(raw);const ev=await prisma.$transaction(async tx=>{const run=await tx.productionRun.findUnique({where:{id:d.productionRunId},include:{productionOrder:{include:{machine:true}}}});if(!run||run.productionOrder.machine.plantId!==s.plantId)throw Object.assign(new Error('التشغيل غير موجود'),{status:404});const end=new Date();const start=new Date(end.getTime()-d.durationMin*60000);const e=await tx.downtimeEvent.create({data:{productionRunId:d.productionRunId,codeId:d.codeId,startTime:start,endTime:end,durationMin:d.durationMin,notes:d.notes}});await tx.productionRun.update({where:{id:d.productionRunId},data:{downtimeMin:{increment:d.durationMin}}});await audit(tx,{userId:s.userId,entityType:'DowntimeEvent',entityId:e.id,action:'CREATE_MANUAL',after:d});return e});return Response.json({ok:true,event:ev},{status:201});
}catch(e){return apiError(e)}}
