import {prisma} from '@/lib/prisma'; import {requireUser,apiError} from '@/lib/rbac'; import {cairoPeriod} from '@/lib/date'; import {runOee} from '@/lib/costing';
export async function GET(){try{const s=await requireUser();const {startDay,startMonth}=cairoPeriod();
 const canFinance=s.roles.includes('OWNER')||s.roles.includes('FINANCE');const canCost=canFinance||s.roles.includes('PRODUCTION_MANAGER');
 const [todayRuns,monthRuns,lots,holds,machines,dbAlerts,openMaintenance,lowSpares,customerInvoices,supplierInvoices,openApprovals]=await Promise.all([
  prisma.productionRun.findMany({where:{startTime:{gte:startDay},productionOrder:{machine:{plantId:s.plantId}}},include:{productionOrder:{include:{machine:true,product:true}}}}),
  prisma.productionRun.findMany({where:{startTime:{gte:startMonth},productionOrder:{machine:{plantId:s.plantId}}}}),
  prisma.inventoryLot.findMany({where:{warehouse:{plantId:s.plantId},material:{type:'POY'},qcStatus:'RELEASED'},select:{availableQtyKg:true}}),
  prisma.qualityHold.count({where:{status:{in:['OPEN','INVESTIGATING']}}}),
  prisma.machine.findMany({where:{plantId:s.plantId},orderBy:{code:'asc'},include:{productionOrders:{where:{runs:{some:{startTime:{gte:startDay}}}},include:{product:true,runs:{where:{startTime:{gte:startDay}}}}}}}),
  prisma.alert.findMany({where:{plantId:s.plantId,status:{in:['OPEN','ACKNOWLEDGED']}},orderBy:[{severity:'desc'},{createdAt:'desc'}],take:10}),
  prisma.maintenanceOrder.count({where:{machine:{plantId:s.plantId},status:{notIn:['CLOSED','CANCELLED']}}}),
  prisma.sparePart.findMany({where:{companyId:s.companyId,active:true},select:{nameAr:true,stockQty:true,minStock:true}}),
  canFinance?prisma.invoice.findMany({where:{customer:{companyId:s.companyId},status:{in:['OPEN','PARTIAL','OVERDUE']}},select:{totalAmount:true,paidAmount:true}}):Promise.resolve([]),
  canFinance?prisma.supplierInvoice.findMany({where:{companyId:s.companyId,status:{in:['OPEN','PARTIAL','OVERDUE']}},select:{totalAmount:true,paidAmount:true}}):Promise.resolve([]),
  s.roles.includes('OWNER')?prisma.approvalRequest.count({where:{companyId:s.companyId,status:'PENDING'}}):Promise.resolve(0)
 ]);
 const sum=(xs:any[],key:string)=>xs.reduce((a,x)=>a+Number(x[key]||0),0); const todayA=sum(todayRuns,'gradeAKg');const todayB=sum(todayRuns,'gradeBKg');const todayWaste=sum(todayRuns,'wasteKg');const todayInput=sum(todayRuns,'inputKg');const monthSaleable=sum(monthRuns,'gradeAKg')+sum(monthRuns,'gradeBKg');const monthWaste=sum(monthRuns,'wasteKg');const monthInput=sum(monthRuns,'inputKg');const poyStock=lots.reduce((a,x)=>a+Number(x.availableQtyKg),0);const dailyPoy=(300000/30)/0.98;const daysCover=dailyPoy>0?poyStock/dailyPoy:0;
 let oeeWeighted=0,oeeKg=0,costValue=0,costKg=0; for(const r of monthRuns){const out=Number(r.gradeAKg)+Number(r.gradeBKg);if(out>0){const full=await prisma.productionRun.findUnique({where:{id:r.id},include:{productionOrder:true,costSnapshot:true}});if(full){const om=await runOee(prisma,full);oeeWeighted+=om.oee*out;oeeKg+=out;if(full.costSnapshot){costValue+=Number(full.costSnapshot.fullCostEgpKg)*out;costKg+=out}}}} const avgOee=oeeKg>0?oeeWeighted/oeeKg:0;const avgCostKg=costKg>0?costValue/costKg:0;
 const machineRows=machines.map(m=>{const runs=m.productionOrders.flatMap(o=>o.runs);const output=runs.reduce((a,r)=>a+Number(r.gradeAKg)+Number(r.gradeBKg),0);const waste=runs.reduce((a,r)=>a+Number(r.wasteKg),0);const input=runs.reduce((a,r)=>a+Number(r.inputKg),0);const open=m.productionOrders.find(o=>o.runs.some(r=>r.status==='OPEN'));return {code:m.code,nameAr:m.nameAr,spindles:m.spindles,status:m.status,sku:open?.product.nameAr||m.productionOrders[0]?.product.nameAr||'—',outputKg:output,yieldPct:input>0?output/input:0,wastePct:input>0?waste/input:0}});
 const receivables=customerInvoices.reduce((a,x)=>a+Math.max(0,Number(x.totalAmount)-Number(x.paidAmount)),0);const payables=supplierInvoices.reduce((a,x)=>a+Math.max(0,Number(x.totalAmount)-Number(x.paidAmount)),0);
 const alerts=[...dbAlerts.map(a=>({severity:a.severity,text:a.messageAr,action:'فتح التفاصيل'}))];if(daysCover<20)alerts.unshift({severity:'CRITICAL',text:`مخزون POY الإجمالي يكفي ${daysCover.toFixed(1)} يوم فقط`,action:'مراجعة MRP والمشتريات'});if(holds>0)alerts.push({severity:'HIGH',text:`يوجد ${holds} Hold جودة مفتوح`,action:'مراجعة الجودة'});if(openMaintenance>0)alerts.push({severity:'HIGH',text:`يوجد ${openMaintenance} أمر صيانة مفتوح`,action:'مراجعة الصيانة'});const low=lowSpares.filter(x=>Number(x.stockQty)<=Number(x.minStock));if(low.length)alerts.push({severity:'HIGH',text:`${low.length} قطع غيار عند/تحت حد الأمان`,action:'مراجعة مخزون قطع الغيار'});
 return Response.json({ok:true,visibility:{finance:canFinance,cost:canCost,approvals:s.roles.includes('OWNER')},kpis:{todayProductionKg:todayA+todayB,monthProductionKg:monthSaleable,todayYield:todayInput>0?(todayA+todayB)/todayInput:0,monthWastePct:monthInput>0?monthWaste/monthInput:0,poyDaysCover:daysCover,qualityHolds:holds,avgOee,avgCostKg:canCost?avgCostKg:null,openMaintenance,lowSpareCount:low.length,receivables:canFinance?receivables:null,payables:canFinance?payables:null,openApprovals:s.roles.includes('OWNER')?openApprovals:null},machines:machineRows,alerts});
}catch(e){return apiError(e)}}
