'use client';
import {useEffect,useMemo,useState} from 'react';
export default function MachineScreen(){
 const machineCode=process.env.NEXT_PUBLIC_PILOT_MACHINE_CODE||'DTY-CN-02';
 const [ctx,setCtx]=useState<any>(null),[codes,setCodes]=useState<any[]>([]),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[now,setNow]=useState(Date.now());
 const [orderId,setOrderId]=useState(''),[shiftId,setShiftId]=useState(''),[lotId,setLotId]=useState(''),[issue,setIssue]=useState(2700),[stopCode,setStopCode]=useState('');
 const [finish,setFinish]=useState({gradeAKg:0,gradeBKg:0,wasteKg:0,electricityKwh:0,downtimeMin:0});
 async function load(){const [a,b]=await Promise.all([fetch(`/api/production/operator-context?machine=${machineCode}`),fetch('/api/production/downtime')]);const j=await a.json(),dj=await b.json();setCtx(j);if(a.ok){if(j.orders?.[0]&&!orderId)setOrderId(j.orders[0].id);if(j.shifts?.[0]&&!shiftId)setShiftId(j.shifts[0].id);if(j.lots?.[0]&&!lotId)setLotId(j.lots[0].id)}if(b.ok){setCodes(dj.codes);if(dj.codes?.[0]&&!stopCode)setStopCode(dj.codes[0].id)}}
 useEffect(()=>{load()},[]);useEffect(()=>{const i=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(i)},[]);
 async function start(){setBusy(true);const r=await fetch('/api/production/runs/start',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({productionOrderId:orderId,shiftId,poyLotId:lotId,poyIssueKg:issue})});const j=await r.json();setBusy(false);setMsg(r.ok?'تم بدء التشغيل وصرف POY تلقائيًا':j.error||'تعذر البدء');await load()}
 async function startDowntime(){if(!ctx?.openRun||!stopCode)return;setBusy(true);const r=await fetch('/api/production/downtime',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'START',productionRunId:ctx.openRun.id,codeId:stopCode})});const j=await r.json();setBusy(false);setMsg(r.ok?'تم تسجيل توقف الماكينة وبدء العداد':j.error);await load()}
 async function stopDowntime(){const ev=ctx?.openRun?.downtimeEvents?.[0];if(!ev)return;setBusy(true);const r=await fetch('/api/production/downtime',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'STOP',eventId:ev.id})});const j=await r.json();setBusy(false);setMsg(r.ok?`تم استئناف التشغيل — التوقف ${j.event.durationMin} دقيقة`:j.error);await load()}
 async function complete(){if(!ctx?.openRun)return;if(ctx.openRun.downtimeEvents?.length){setMsg('يجب استئناف الماكينة وإغلاق عداد التوقف قبل إنهاء التشغيل');return}setBusy(true);const payload={...finish,downtimeMin:Math.max(Number(ctx.openRun.downtimeMin||0),finish.downtimeMin)};const r=await fetch(`/api/production/runs/${ctx.openRun.id}/complete`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();setBusy(false);setMsg(r.ok?'تم إقفال التشغيل وإنشاء Lot المنتج التام بانتظار الجودة':j.error||'تعذر الإقفال');await load()}
 const open=ctx?.openRun,liveStop=open?.downtimeEvents?.[0];const balance=useMemo(()=>finish.gradeAKg+finish.gradeBKg+finish.wasteKg,[finish]);const elapsed=liveStop?Math.max(0,Math.floor((now-new Date(liveStop.startTime).getTime())/1000)):0;const mm=String(Math.floor(elapsed/60)).padStart(2,'0'),ss=String(elapsed%60).padStart(2,'0');
 if(!ctx)return <div className="panel">جاري تحميل شاشة الماكينة...</div>;
 return <><header className="pageHead"><div><h1>شاشة العامل — {ctx.machine?.nameAr}</h1><p>{ctx.machine?.code} • Pilot Arabic Shop-Floor</p></div><span className={`bigState ${liveStop?'off':open?'on':'off'}`}>{liveStop?'متوقفة':open?'تشغيل':'جاهزة'}</span></header>
 {!open?<div className="panel formPanel"><h2>بدء تشغيل جديد</h2><div className="formGrid"><label>أمر الإنتاج<select value={orderId} onChange={e=>setOrderId(e.target.value)}>{ctx.orders?.map((o:any)=><option key={o.id} value={o.id}>{o.orderNo} — {o.product.nameAr}</option>)}</select></label><label>الوردية<select value={shiftId} onChange={e=>setShiftId(e.target.value)}>{ctx.shifts?.map((s:any)=><option key={s.id} value={s.id}>{s.nameAr}</option>)}</select></label><label>Lot POY<select value={lotId} onChange={e=>setLotId(e.target.value)}>{ctx.lots?.map((l:any)=><option key={l.id} value={l.id}>{l.lotNo} — {l.material.nameAr} — {Number(l.availableQtyKg).toLocaleString()} كجم</option>)}</select></label><label>كمية الصرف kg<input type="number" value={issue} onChange={e=>setIssue(Number(e.target.value))}/></label></div><button className="primary actionLarge" disabled={busy||!orderId||!lotId} onClick={start}>{busy?'جاري التنفيذ...':'بدء التشغيل وصرف الخامة'}</button></div>:
 <><div className="machineHero"><div><span>أمر الإنتاج</span><b className="ltr">{open.productionOrder.orderNo}</b></div><div><span>الصنف</span><b>{open.productionOrder.product.nameAr}</b></div><div><span>POY Lot</span><b className="ltr">{open.materialIssues?.[0]?.inventoryLot?.lotNo}</b></div><div><span>Input</span><b>{Number(open.inputKg).toLocaleString()} كجم</b></div></div>
 <div className={`panel downtimeLive ${liveStop?'stopped':''}`}><div><h2>{liveStop?'الماكينة متوقفة الآن':'تسجيل توقف مباشر'}</h2>{liveStop?<><b className="timer">{mm}:{ss}</b><p>{liveStop.code?.nameAr}</p></>:<div className="formGrid"><label>سبب التوقف<select value={stopCode} onChange={e=>setStopCode(e.target.value)}>{codes.map((c:any)=><option key={c.id} value={c.id}>{c.nameAr}</option>)}</select></label></div>}</div>{liveStop?<button className="primary greenAction" disabled={busy} onClick={stopDowntime}>استئناف التشغيل وإيقاف العداد</button>:<button className="dangerAction" disabled={busy||!stopCode} onClick={startDowntime}>توقفت الماكينة — ابدأ العداد</button>}</div>
 <div className="panel formPanel"><h2>إقفال الوردية / التشغيل</h2><p className="hint">يجب أن يتزن Input = درجة أولى + درجة ثانية + هالك. زمن التوقف يُحسب تلقائيًا من Live Timer.</p><div className="formGrid">{([['gradeAKg','إنتاج درجة أولى kg'],['gradeBKg','إنتاج درجة ثانية kg'],['wasteKg','هالك kg'],['electricityKwh','كهرباء kWh']] as const).map(([k,l])=><label key={k}>{l}<input type="number" value={finish[k]} onChange={e=>setFinish({...finish,[k]:Number(e.target.value)})}/></label>)}<div className={`balanceBox ${Math.abs(Number(open.inputKg)-balance)<=Math.max(2,Number(open.inputKg)*.005)?'balanced':'unbalanced'}`}><span>المجموع المسجل</span><b>{balance.toLocaleString()} / {Number(open.inputKg).toLocaleString()} كجم</b></div><div className="balanceBox"><span>التوقف المسجل حتى الآن</span><b>{Number(open.downtimeMin||0)} دقيقة</b></div></div><button className="primary actionLarge" disabled={busy||!!liveStop} onClick={complete}>{liveStop?'أغلق التوقف أولًا':busy?'جاري الإقفال...':'إنهاء التشغيل وإنشاء Lot DTY'}</button></div></>}
 {msg&&<div className="panel message"><b>{msg}</b></div>}</>}
