'use client';
import {useEffect,useState} from 'react';
export default function Maintenance(){
 const [orders,setOrders]=useState<any[]>([]),[ctx,setCtx]=useState<any>({machines:[],plans:[],spares:[]}),[monthly,setMonthly]=useState<any>({rows:[],recommendations:[]}),[msg,setMsg]=useState('');
 const [form,setForm]=useState({machineId:'',type:'BREAKDOWN',priority:'NORMAL',notes:''});const [close,setClose]=useState<any>({id:'',rootCause:'',laborHours:0,externalCost:0,sparePartId:'',qty:0});
 async function load(){const[a,b,c]=await Promise.all([fetch('/api/maintenance/orders'),fetch('/api/maintenance/context'),fetch('/api/maintenance/monthly-cost?months=6')]);const ja=await a.json(),jb=await b.json(),jc=await c.json();if(a.ok)setOrders(ja.orders);if(b.ok){setCtx(jb);setForm(f=>({...f,machineId:f.machineId||jb.machines?.[0]?.id||''}));setClose((f:any)=>({...f,sparePartId:f.sparePartId||jb.spares?.[0]?.id||''}))}if(c.ok)setMonthly(jc)}useEffect(()=>{load()},[]);
 async function create(){const r=await fetch('/api/maintenance/orders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)});const j=await r.json();setMsg(r.ok?`تم إنشاء ${j.order.moNo}`:j.error);if(r.ok)load()}
 async function complete(){const spares=close.sparePartId&&close.qty>0?[{sparePartId:close.sparePartId,qty:close.qty}]:[];const r=await fetch(`/api/maintenance/orders/${close.id}/complete`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({rootCause:close.rootCause,laborHours:close.laborHours,externalCost:close.externalCost,spares})});const j=await r.json();setMsg(r.ok?'تم إقفال أمر الصيانة وصرف قطع الغيار':j.error);if(r.ok){setClose({...close,id:'',rootCause:'',qty:0});load()}}
 const currentMonth=new Date().toISOString().slice(0,7),mtd=monthly.rows?.filter((x:any)=>x.month===currentMonth)||[];const mtdCost=mtd.reduce((a:number,x:any)=>a+x.maintenanceCost,0),mtdKg=mtd.reduce((a:number,x:any)=>a+x.productionKg,0);
 return <><header className="pageHead"><div><h1>الصيانة وقطع الغيار</h1><p>Preventive • Breakdown • Actual Maintenance Cost / Machine / Month</p></div></header>{msg&&<div className="formNotice">{msg}</div>}
 <div className="kpiGrid"><div className="kpi"><span>تكلفة الصيانة هذا الشهر</span><strong>{(mtdCost/1000).toFixed(1)} ألف</strong><small>عمالة + Spares + External</small></div><div className="kpi"><span>Maintenance EGP/kg</span><strong>{mtdKg?`${(mtdCost/mtdKg).toFixed(2)} ج`:'—'}</strong><small>على إنتاج الشهر الحالي</small></div><div className="kpi"><span>أوامر مفتوحة</span><strong>{orders.filter((o:any)=>!['CLOSED','CANCELLED'].includes(o.status)).length}</strong><small>تحتاج متابعة</small></div></div>
 <div className="grid2"><div className="panel formPanel"><h2>أمر صيانة جديد</h2><div className="formGrid"><label>الماكينة<select value={form.machineId} onChange={e=>setForm({...form,machineId:e.target.value})}>{ctx.machines.map((m:any)=><option key={m.id} value={m.id}>{m.nameAr}</option>)}</select></label><label>النوع<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="BREAKDOWN">عطل</option><option value="PREVENTIVE">وقائية</option><option value="INSPECTION">فحص</option></select></label><label>الأولوية<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value="NORMAL">عادي</option><option value="HIGH">عالي</option><option value="URGENT">عاجل</option></select></label><label>ملاحظات<input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><button className="primary" onClick={create}>فتح أمر الصيانة</button></div><div className="panel"><h2>قطع الغيار</h2><table><thead><tr><th>القطعة</th><th>الرصيد</th><th>Min</th><th>التكلفة</th></tr></thead><tbody>{ctx.spares.map((s:any)=><tr key={s.id}><td>{s.nameAr}<small className="ltr">{s.code}</small></td><td className={Number(s.stockQty)<=Number(s.minStock)?'redText':''}>{Number(s.stockQty)}</td><td>{Number(s.minStock)}</td><td>{Number(s.unitCostEgp).toLocaleString()} ج</td></tr>)}</tbody></table></div></div>
 <div className="panel"><h2>أوامر الصيانة</h2><div className="tableWrap"><table><thead><tr><th>MO</th><th>الماكينة</th><th>النوع</th><th>الأولوية</th><th>الحالة</th><th>فتح</th><th>إقفال</th></tr></thead><tbody>{orders.map((o:any)=><tr key={o.id}><td className="ltr">{o.moNo}</td><td>{o.machine.nameAr}</td><td>{o.type}</td><td>{o.priority}</td><td>{o.status}</td><td>{new Date(o.openedAt).toLocaleString('ar-EG')}</td><td>{o.status!=='CLOSED'&&<button onClick={()=>setClose({...close,id:o.id})}>إقفال</button>}</td></tr>)}</tbody></table></div></div>
 {close.id&&<div className="panel formPanel"><h2>إقفال أمر الصيانة</h2><div className="formGrid"><label>Root Cause<input value={close.rootCause} onChange={e=>setClose({...close,rootCause:e.target.value})}/></label><label>ساعات العمل<input type="number" value={close.laborHours} onChange={e=>setClose({...close,laborHours:Number(e.target.value)})}/></label><label>تكلفة خارجية<input type="number" value={close.externalCost} onChange={e=>setClose({...close,externalCost:Number(e.target.value)})}/></label><label>قطعة غيار<select value={close.sparePartId} onChange={e=>setClose({...close,sparePartId:e.target.value})}><option value="">بدون</option>{ctx.spares.map((s:any)=><option key={s.id} value={s.id}>{s.nameAr} — رصيد {Number(s.stockQty)}</option>)}</select></label><label>الكمية<input type="number" value={close.qty} onChange={e=>setClose({...close,qty:Number(e.target.value)})}/></label></div><button className="primary" onClick={complete}>اعتماد الإقفال</button></div>}
 <div className="panel"><h2>التكلفة الفعلية للصيانة حسب الماكينة — آخر 6 أشهر</h2><div className="tableWrap"><table><thead><tr><th>الشهر</th><th>الماكينة</th><th>أوامر</th><th>Spares</th><th>Labor</th><th>External</th><th>Total</th><th>Production kg</th><th>EGP/kg</th><th>Actual EGP/hour</th></tr></thead><tbody>{monthly.rows?.map((r:any)=><tr key={`${r.month}-${r.machineId}`}><td className="ltr">{r.month}</td><td>{r.machineName}</td><td>{r.orders}</td><td>{r.sparesCost.toFixed(0)}</td><td>{r.laborCost.toFixed(0)}</td><td>{r.externalCost.toFixed(0)}</td><td><b>{r.maintenanceCost.toFixed(0)}</b></td><td>{r.productionKg.toFixed(0)}</td><td>{r.maintenanceEgpKg.toFixed(2)}</td><td>{r.actualMaintenanceEgpHour.toFixed(0)}</td></tr>)}</tbody></table></div></div>
 <div className="panel"><h2>معدل الصيانة المقترح من آخر 90 يوم</h2><table><thead><tr><th>الماكينة</th><th>Actual Cost 90d</th><th>Run Hours</th><th>Recommended EGP/hour</th></tr></thead><tbody>{monthly.recommendations?.map((r:any)=><tr key={r.machineId}><td>{r.machineName}</td><td>{r.actualCost90d.toFixed(0)} ج</td><td>{r.runHours90d.toFixed(1)}</td><td><b>{r.recommendedMaintenanceEgpHour.toFixed(0)} ج/ساعة</b></td></tr>)}</tbody></table><p className="hint">لا يتم تعديل Machine Cost Rate تلقائيًا في V0.6؛ الرقم المقترح يحتاج مراجعة الإدارة قبل اعتماده في الـCosting Engine.</p></div>
 <div className="panel"><h2>الصيانة الوقائية القادمة</h2><table><thead><tr><th>الماكينة</th><th>المهمة</th><th>الاستحقاق</th></tr></thead><tbody>{ctx.plans.map((p:any)=><tr key={p.id}><td>{p.machine.nameAr}</td><td>{p.nameAr}</td><td>{p.nextDueAt?new Date(p.nextDueAt).toLocaleDateString('ar-EG'):'—'}</td></tr>)}</tbody></table></div></>}
