import Link from 'next/link';import {getSession} from '@/lib/session';import {LogoutButton} from './LogoutButton';
type Item={label:string;href:string;roles?:string[]};
const items:Item[]=[
 {label:'الرئيسية',href:'/'},
 {label:'مخزون POY',href:'/inventory',roles:['OWNER','WAREHOUSE','PRODUCTION_MANAGER','QUALITY','PROCUREMENT']},{label:'مخزون DTY',href:'/inventory/finished',roles:['OWNER','WAREHOUSE','PRODUCTION_MANAGER','QUALITY','SALES']},{label:'حركة مخزون',href:'/inventory/movements',roles:['OWNER','WAREHOUSE']},{label:'الجرد الفعلي',href:'/inventory/counts',roles:['OWNER','WAREHOUSE']},{label:'مسح QR',href:'/inventory/scan',roles:['OWNER','WAREHOUSE','QUALITY','PRODUCTION_MANAGER']},{label:'ملصقات QR',href:'/inventory/labels',roles:['OWNER','WAREHOUSE']},
 {label:'تخطيط الإنتاج',href:'/production/planning',roles:['OWNER','PRODUCTION_MANAGER']},{label:'أوامر الإنتاج',href:'/production/orders',roles:['OWNER','PRODUCTION_MANAGER']},{label:'شاشة العامل',href:'/production/machine',roles:['OWNER','PRODUCTION_MANAGER','OPERATOR']},{label:'OEE والتوقفات',href:'/production/oee',roles:['OWNER','PRODUCTION_MANAGER','MAINTENANCE']},
 {label:'الجودة',href:'/quality',roles:['OWNER','QUALITY']},{label:'اختبارات QC',href:'/quality/tests',roles:['OWNER','QUALITY']},{label:'تتبع Lot',href:'/traceability',roles:['OWNER','QUALITY','WAREHOUSE','PRODUCTION_MANAGER','SALES','PROCUREMENT']},
 {label:'MRP',href:'/procurement/mrp',roles:['OWNER','PROCUREMENT','PRODUCTION_MANAGER']},{label:'RFQ وعروض الموردين',href:'/procurement/rfq',roles:['OWNER','PROCUREMENT','PRODUCTION_MANAGER']},{label:'أوامر الشراء',href:'/procurement/orders',roles:['OWNER','PROCUREMENT']},{label:'استلام POY',href:'/procurement/receipts',roles:['OWNER','PROCUREMENT','WAREHOUSE']},
 {label:'عروض أسعار العملاء',href:'/sales/quotations',roles:['OWNER','SALES']},{label:'أوامر البيع',href:'/sales/orders',roles:['OWNER','SALES']},{label:'العملاء والتحصيل',href:'/finance/receivables',roles:['OWNER','FINANCE','SALES']},{label:'مستحقات الموردين',href:'/finance/payables',roles:['OWNER','FINANCE']},
 {label:'الصيانة',href:'/maintenance',roles:['OWNER','MAINTENANCE','PRODUCTION_MANAGER']},{label:'التكلفة والربحية',href:'/costing',roles:['OWNER','FINANCE','PRODUCTION_MANAGER']},{label:'تقييم الموردين',href:'/analytics/suppliers',roles:['OWNER','PROCUREMENT','FINANCE']},{label:'ربحية العملاء',href:'/analytics/customers',roles:['OWNER','FINANCE','SALES']},
 {label:'مساعد المصنع AI',href:'/assistant',roles:['OWNER','PRODUCTION_MANAGER','QUALITY','PROCUREMENT','SALES','FINANCE','MAINTENANCE']},{label:'الاعتمادات',href:'/approvals',roles:['OWNER']},{label:'التنبيهات',href:'/alerts',roles:['OWNER']},{label:'تقارير الإدارة',href:'/reports',roles:['OWNER','FINANCE']},{label:'Pilot الجاهزية',href:'/pilot',roles:['OWNER','PRODUCTION_MANAGER']},
 {label:'البيانات الأساسية',href:'/master-data',roles:['OWNER']},{label:'المستخدمون',href:'/admin/users',roles:['OWNER']},{label:'سجل التدقيق',href:'/admin/audit',roles:['OWNER']},{label:'إعدادات النظام',href:'/settings',roles:['OWNER']}
];
export async function Sidebar(){const s=await getSession();if(!s)return null;const visible=items.filter(i=>!i.roles||s.roles.includes('OWNER')||i.roles.some(r=>s.roles.includes(r)));return <aside className="sidebar"><div className="brand"><strong>DTY ERP</strong><span>نظام إدارة المصنع</span></div><nav>{visible.map(i=><Link key={i.href} className="navItem" href={i.href}>{i.label}</Link>)}</nav><div className="sidebarFoot">مصنع 2100 • {s.username}<br/>العربية RTL<LogoutButton/></div></aside>}
