import fs from 'node:fs';import path from 'node:path';
const root=new URL('..',import.meta.url);const base=new URL('.',root).pathname;
const read=p=>fs.readFileSync(new URL(p,root),'utf8');const exists=p=>fs.existsSync(new URL(p,root));
const schema=read('prisma/schema.prisma'),seed=read('prisma/seed.ts'),pkg=JSON.parse(read('package.json'));
const requiredModels=['Company','Plant','User','Role','Permission','AuditLog','Material','Product','Machine','InventoryLot','ProductionPlan','ProductionOrder','ProductionRun','FinishedLot','QualitySpec','QualityHold','Rfq','SupplierQuote','PurchaseOrder','SupplierInvoice','SupplierPayment','SalesQuotation','SalesOrder','Delivery','Invoice','Collection','CostSnapshot','MaintenanceOrder','SparePart','StockCount','SystemSetting','CustomerCostAdjustment','ApprovalRequest','IntegrationEvent'];
const requiredRoutes=['src/app/api/auth/login/route.ts','src/app/api/inventory/movements/route.ts','src/app/api/inventory/counts/route.ts','src/app/api/production/plans/route.ts','src/app/api/production/runs/start/route.ts','src/app/api/production/downtime/route.ts','src/app/api/quality/holds/route.ts','src/app/api/quality/tests/route.ts','src/app/api/procurement/mrp/route.ts','src/app/api/procurement/rfq/route.ts','src/app/api/sales/quotations/route.ts','src/app/api/sales/orders/route.ts','src/app/api/finance/payables/route.ts','src/app/api/costing/runs/route.ts','src/app/api/maintenance/orders/route.ts','src/app/api/analytics/suppliers/route.ts','src/app/api/analytics/customers/route.ts','src/app/api/approvals/route.ts','src/app/api/integrations/outbox/dispatch/route.ts','src/app/api/admin/users/route.ts','src/app/api/admin/audit/route.ts','src/app/api/reports/management/route.ts','src/app/api/pilot/readiness/route.ts','src/app/api/assistant/route.ts','src/app/api/inventory/finished/route.ts','src/app/api/master-data/[entity]/route.ts','src/app/api/alerts/route.ts'];
const requiredPages=['src/app/page.tsx','src/app/production/planning/page.tsx','src/app/production/machine/page.tsx','src/app/procurement/rfq/page.tsx','src/app/sales/quotations/page.tsx','src/app/inventory/counts/page.tsx','src/app/quality/tests/page.tsx','src/app/finance/payables/page.tsx','src/app/maintenance/page.tsx','src/app/analytics/suppliers/page.tsx','src/app/analytics/customers/page.tsx','src/app/approvals/page.tsx','src/app/reports/page.tsx','src/app/master-data/page.tsx','src/app/admin/users/page.tsx','src/app/admin/audit/page.tsx','src/app/pilot/page.tsx','src/app/assistant/page.tsx','src/app/inventory/finished/page.tsx','src/app/alerts/page.tsx','src/app/settings/page.tsx'];
const requiredPermissions=['inventory.read','inventory.count','production.plan','production.run','quality.release','procurement.rfq','sales.quotation','finance.ap','costing.read','maintenance.read','master.read','master.write','admin.users','audit.read','alerts.manage','reports.read','approvals.decide','integrations.dispatch','pilot.read','ai.assistant'];
const missingModels=requiredModels.filter(m=>!schema.includes(`model ${m} {`)),missingFiles=[...requiredRoutes,...requiredPages].filter(p=>!exists(p)),missingPermissions=requiredPermissions.filter(p=>!seed.includes(`'${p}'`));
const spindles=[214,240,240,240,240,240].reduce((a,b)=>a+b,0);const appFiles=[];function walk(dir){for(const f of fs.readdirSync(dir)){const p=path.join(dir,f),st=fs.statSync(p);if(st.isDirectory())walk(p);else if(/\.(ts|tsx)$/.test(f))appFiles.push(p)}}walk(new URL('src/app',root).pathname);const mockImports=appFiles.filter(p=>fs.readFileSync(p,'utf8').includes('mock-data'));
const models=[...schema.matchAll(/^model\s+(\w+)\s*\{/gm)].map(x=>x[1]),enums=[...schema.matchAll(/^enum\s+(\w+)\s*\{/gm)].map(x=>x[1]);
const routeFiles=[];const pageFiles=[];function collect(dir){for(const f of fs.readdirSync(dir)){const p=path.join(dir,f),st=fs.statSync(p);if(st.isDirectory())collect(p);else{if(f==='route.ts')routeFiles.push(p);if(f==='page.tsx')pageFiles.push(p)}}}collect(new URL('src/app',root).pathname);
const errors=[];
if(missingModels.length)errors.push('Missing models: '+missingModels.join(','));if(missingFiles.length)errors.push('Missing files: '+missingFiles.join(','));if(missingPermissions.length)errors.push('Missing permissions: '+missingPermissions.join(','));if(spindles!==1414)errors.push('Spindles mismatch');if(mockImports.length)errors.push('Mock data found');if(!seed.includes("['owner','الإدارة العليا'"))errors.push('Owner demo user missing');
if(!read('middleware.ts').includes('sameOrigin'))errors.push('Same-origin write protection missing');if(!read('src/app/api/auth/login/route.ts').includes('rateCheck'))errors.push('Login rate limiting missing');
if(errors.length){console.error(JSON.stringify({ok:false,errors},null,2));process.exit(1)}
console.log(JSON.stringify({ok:true,version:pkg.version,models:models.length,enums:enums.length,criticalModels:requiredModels.length,routes:routeFiles.length,criticalRoutes:requiredRoutes.length,pages:pageFiles.length,criticalPages:requiredPages.length,permissions:requiredPermissions.length,seedMachines:6,totalSpindles:spindles,arabicFirst:true,roleAwareNavigation:true,multiCompanyReady:true,sameOriginWrites:true,loginRateLimit:true,fullScope:['planning','mrp','rfq','procurement','inventory','stock-count','production','quality','sales-quotation','sales-order','dispatch','ar','ap','costing','maintenance','analytics','approvals','alerts','audit','settings','reports','integrations','pilot','ai-assistant','finished-goods','master-data']},null,2));
