import {prisma} from '@/lib/prisma';import {requirePermission,apiError} from '@/lib/rbac';
const n=(v:any)=>Number(v||0);
export async function GET(req:Request){try{const s=await requirePermission('maintenance.read');const u=new URL(req.url);const months=Math.max(1,Math.min(12,Number(u.searchParams.get('months')||6)));const start=new Date();start.setDate(1);start.setHours(0,0,0,0);start.setMonth(start.getMonth()-(months-1));const [orders,runs,cfg,machines]=await Promise.all([
 prisma.maintenanceOrder.findMany({where:{machine:{plantId:s.plantId},completedAt:{gte:start},status:'CLOSED'},include:{machine:true,spares:true}}),
 prisma.productionRun.findMany({where:{endTime:{gte:start},status:{in:['COMPLETED','CLOSED']},productionOrder:{machine:{plantId:s.plantId}}},include:{productionOrder:{include:{machine:true}}}}),
 prisma.costConfig.findFirst({where:{plantId:s.plantId,active:true},orderBy:{effectiveFrom:'desc'}}),
 prisma.machine.findMany({where:{plantId:s.plantId},orderBy:{code:'asc'}})
 ]);const laborRate=cfg?n(cfg.laborEgpHour):0;const map=new Map<string,any>();function key(machineId:string,d:Date){return `${machineId}|${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
 for(const m of machines){for(let i=0;i<months;i++){const d=new Date();d.setDate(1);d.setMonth(d.getMonth()-i);const k=key(m.id,d);map.set(k,{machineId:m.id,machineCode:m.code,machineName:m.nameAr,month:k.split('|')[1],maintenanceCost:0,sparesCost:0,laborCost:0,externalCost:0,orders:0,productionKg:0,runHours:0})}}
 for(const o of orders){if(!o.completedAt)continue;const r=map.get(key(o.machineId,new Date(o.completedAt)));if(!r)continue;const sp=o.spares.reduce((a:any,x:any)=>a+n(x.costEgp),0),lab=n(o.laborHours)*laborRate,ext=n(o.externalCost);r.sparesCost+=sp;r.laborCost+=lab;r.externalCost+=ext;r.maintenanceCost+=sp+lab+ext;r.orders++}
 for(const run of runs){if(!run.endTime)continue;const r=map.get(key(run.productionOrder.machineId,new Date(run.endTime)));if(!r)continue;r.productionKg+=n(run.gradeAKg)+n(run.gradeBKg);r.runHours+=Math.max(0,(+new Date(run.endTime)-+new Date(run.startTime))/3600000)}
 const rows=[...map.values()].map(r=>({...r,maintenanceEgpKg:r.productionKg?r.maintenanceCost/r.productionKg:0,actualMaintenanceEgpHour:r.runHours?r.maintenanceCost/r.runHours:0})).sort((a,b)=>b.month.localeCompare(a.month)||a.machineCode.localeCompare(b.machineCode));
 const cutoff=new Date(Date.now()-90*86400000);const recent=rows.filter(r=>new Date(`${r.month}-01`)>=new Date(cutoff.getFullYear(),cutoff.getMonth(),1));const recommendations=machines.map(m=>{const x=recent.filter(r=>r.machineId===m.id);const cost=x.reduce((a,r)=>a+r.maintenanceCost,0),hours=x.reduce((a,r)=>a+r.runHours,0);return {machineId:m.id,machineCode:m.code,machineName:m.nameAr,recommendedMaintenanceEgpHour:hours?cost/hours:0,actualCost90d:cost,runHours90d:hours}});return Response.json({ok:true,months,rows,recommendations});}catch(e){return apiError(e)}}
